language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - composer self-update

install:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
    - composer install
    - composer remove phpunit/phpunit && require --dev phpunit/phpunit:^5.7 --update-with-dependencies

script: vendor/bin/phpunit

notifications:
  email:
    - luke.visinoni@gmail.com
